# Generated by Django 6.0 on 2026-03-19 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionsPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('puzzle', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GameFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('vote_count', models.IntegerField(default=0)),
                ('approved', models.BooleanField(default=False)),
                ('used_framed_on', models.DateField(blank=True, null=True)),
                ('used_connections_on', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-vote_count'],
            },
        ),
        migrations.CreateModel(
            name='DailyFramed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='film_games.gamefilm')),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('framed', 'Framed'), ('higher_lower', 'Higher or Lower'), ('connections', 'Connections')], max_length=20)),
                ('date', models.DateField()),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'game', 'date')},
            },
        ),
    ]
