# Generated by Django 6.0 on 2026-03-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_games', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConnectionsPuzzle',
        ),
        migrations.RemoveField(
            model_name='gamefilm',
            name='used_connections_on',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='game',
            field=models.CharField(choices=[('framed', 'Framed'), ('higher_lower', 'Higher or Lower')], max_length=20),
        ),
    ]
