# Generated by Django 6.0 on 2026-01-13 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kinorg', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='addition',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addition',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinorg.film'),
        ),
        migrations.AddField(
            model_name='filmlist',
            name='films',
            field=models.ManyToManyField(through='kinorg.Addition', through_fields=('film_list', 'film'), to='kinorg.film'),
        ),
        migrations.AddField(
            model_name='filmlist',
            name='guests',
            field=models.ManyToManyField(related_name='guestlists', related_query_name='guestlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filmlist',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='addition',
            name='film_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinorg.filmlist'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='film_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinorg.filmlist'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tag',
            name='films',
            field=models.ManyToManyField(related_name='tags', related_query_name='tagged', to='kinorg.film'),
        ),
        migrations.AddConstraint(
            model_name='addition',
            constraint=models.UniqueConstraint(fields=('film', 'film_list'), name='unique_film_in_list'),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('to_user', 'film_list'), name='unique_invite_per_list'),
        ),
    ]
