# Generated by Django 5.1 on 2024-09-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='movie_id',
            field=models.CharField(default='000', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
