# Generated by Django 6.0 on 2026-02-16 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='backdrop_path',
            field=models.CharField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='cast',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='crew',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='overview',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='film',
            name='production_companies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='runtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WatchedFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('stars', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating out of 5 stars')),
                ('mini_review', models.CharField(blank=True, help_text='Quick thoughts (280 characters max)', max_length=280)),
                ('review_visible', models.BooleanField(default=True, help_text='Show review to other users (you can hide if flagged)')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='kinorg.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_films', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddConstraint(
            model_name='watchedfilm',
            constraint=models.UniqueConstraint(fields=('user', 'film'), name='unique_watched_film_per_user'),
        ),
    ]
