# Generated by Django 5.1 on 2024-09-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0002_film_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='movie_id',
            field=models.IntegerField(unique=True),
        ),
    ]
