# Generated by Django 6.0 on 2026-03-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0003_film_backdrop_path_film_cast_film_crew_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedfilm',
            name='mini_review',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AlterField(
            model_name='watchedfilm',
            name='review_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='watchedfilm',
            name='stars',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
    ]
