# Generated by Django 6.0 on 2026-03-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0004_alter_watchedfilm_mini_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='primary_country',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AddField(
            model_name='film',
            name='production_countries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
