# Generated by Django 5.1 on 2024-09-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0005_filmlist_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(default=1900),
            preserve_default=False,
        ),
    ]
