# Generated by Django 6.0 on 2026-03-20 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0005_add_production_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCCScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('pcc_url', models.URLField()),
            ],
        ),
    ]
