# Generated by Django 5.1 on 2024-09-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0006_film_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='small_poster',
            field=models.CharField(blank=True),
        ),
    ]
