# Generated by Django 6.0 on 2026-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0006_pccscreening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pccscreening',
            name='tmdb_id',
        ),
        migrations.AddField(
            model_name='pccscreening',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='pccscreening',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
