# Generated by Django 5.1 on 2024-09-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0007_film_small_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='small_poster',
            new_name='poster_path',
        ),
    ]
