# Generated by Django 6.0 on 2026-03-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0007_remove_pccscreening_tmdb_id_pccscreening_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pccscreening',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
