# Generated by Django 5.1 on 2024-09-17 10:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0008_rename_small_poster_film_poster_path'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='addition',
            constraint=models.UniqueConstraint(fields=('film', 'film_list'), name='unique_film_in_list'),
        ),
    ]
