# Generated by Django 6.0 on 2026-03-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0008_alter_pccscreening_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='collections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
