# Generated by Django 6.0 on 2026-03-23 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0009_film_collections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='watchedfilm',
            name='flagged_by',
            field=models.ManyToManyField(blank=True, related_name='flagged_reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
