# Generated by Django 5.2.1 on 2025-07-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0011_invitation_unique_invite_per_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmlist',
            name='films',
            field=models.ManyToManyField(through='kinorg.Addition', through_fields=('film_list', 'film'), to='kinorg.film'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('films', models.ManyToManyField(related_name='tags', related_query_name='tagged', to='kinorg.film')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
