# Generated by Django 6.0 on 2026-03-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0011_likedfilm'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='collection_ranks',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
