# Generated by Django 6.0 on 2026-03-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0012_add_collection_ranks'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='media_type',
            field=models.CharField(blank=True, default='movie', max_length=10),
        ),
    ]
