# Generated by Django 6.0 on 2026-03-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0014_pccscreening_film_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchedfilm',
            name='stars',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
