# Generated by Django 6.0 on 2026-04-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0017_watchlist_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='similar_film_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
