# Generated by Django 6.0 on 2026-04-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0018_add_similar_film_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='film',
            name='videos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='film',
            name='watch_providers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
