# Generated by Django 6.0 on 2026-04-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0019_add_videos_watch_providers_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='primary_country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2),
        ),
    ]
