# Generated by Django 6.0.4 on 2026-04-23 08:45

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kinorg', '0021_add_collections_gin_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pccscreening',
            name='pcc_url',
            field=models.URLField(unique=True),
        ),
        migrations.AddIndex(
            model_name='film',
            index=django.contrib.postgres.indexes.GinIndex(fields=['genres'], name='film_genres_gin'),
        ),
        migrations.AddIndex(
            model_name='film',
            index=models.Index(fields=['title'], name='film_title_idx'),
        ),
        migrations.AddIndex(
            model_name='watchedfilm',
            index=models.Index(fields=['-watched_at'], name='watchedfilm_watched_at_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlistitem',
            index=models.Index(fields=['-added_at'], name='watchlistitem_added_at_idx'),
        ),
    ]
